Silly little things (#37)
* Stop testing on RISC-V until we have it actually supported.

* Tweak issue templates

* Tinkering with metadata

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -80,6 +80,8 @@ jobs:
             toolchain: 'clang'
           - platform: { os: 'omnios' }
             toolchain: 'clang'
+          # Skip RISC-V because, well, I haven't worked on adding support for it.
+          - arch: 'riscv64'
         include:
           # Use specific 'egcc' command for packaged GCC on OpenBSD
           - platform: { os: 'openbsd' }
@@ -177,7 +179,7 @@ jobs:
               fi
               # The key is the unique job identifier, e.g., "freebsd-x86_64-gcc"
               # The value is "passing" or "failing" for Shields.io color coding
-              SHIELD_STATUS=$([[ $result == 'success' ]] && echo 'passing' || echo 'failing')
+              SHIELD_STATUS=$([[ $result == 'success' ]] && echo '👍🏽 passing' || echo '👎🏽 failing')
               echo "\"$filename\": \"$SHIELD_STATUS\"" >> $STATUS_JSON
               is_first_json_entry=false
             done
